ProjetoFinal_RodrigoPaulino/Controllers/LojasModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoFinal_RodrigoPaulino.Data;
using ProjetoFinal_RodrigoPaulino.Models;
using ProjetoFinal_RodrigoPaulino.Repositorio;

namespace ProjetoFinal_RodrigoPaulino.Controllers
{

   /// <summary>
   /// controller para 
   /// </summary>
    public class LojasModelsController : Controller
    {

        /// <summary>
        /// variavel somente para leitura 
        /// </summary>
        private readonly BancoContext _context;

        /// <summary>
        /// para gravar precisamos injetar o BancoContext aqui 
        /// criamos tambem uma variavel privada para usarmos nessa classe
        /// fazendo a injeção de dependencia
        /// </summary>
        public LojasModelsController(BancoContext context)
        {
            _context = context;
        }

        // GET: LojasModels
        public async Task<IActionResult> Index()
        {
            return _context.Lojas != null ?
                        View(await _context.Lojas.ToListAsync()) :
                        Problem("Erro ao efetuar o cadastro, tente novamente mais tarde");
            //Entity set 'BancoContext.Lojas' is null.
        }

        // GET: LojasModels/Details/5
        /// <summary>
        /// método que exibe os detalhes da loja
        /// pegando o id como parametro
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            //condição onde se a id ou o banco forem nulos
            if (id == null || _context.Lojas == null)
            {
                return NotFound();
            }
            //retornamos uma busca pelo primeiro
            //ou unico registro do banco passando uma
            //expressao lambda

            var lojasModel = await _context.Lojas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lojasModel == null)
            {
                return NotFound();
            }

            return View(lojasModel);
        }

        // GET: LojasModels/Create
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// método que apaga de fato do banco de dados
        /// usando o id como parametro de entrada
        /// </summary>      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Localizacao,Seguimento,Telefone")] LojasModel lojasModel)
        {
            lojasModel.Nome = lojasModel.Nome.ToUpper();
            _context.Add(lojasModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
           
        }

        // GET: LojasModels/Edit/5
        /// <summary>
        /// método para iditar uma loja no banco
        /// pegando o id como parametro
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Lojas == null)
            {
                return NotFound();
            }

            //Se uma entidade com os valores de chave primária existentes existir no contexto,
            //ela será retornada imediatamente sem fazer uma solicitação para o repositório.
            var lojasModel = await _context.Lojas.FindAsync(id);
            if (lojasModel == null)
            {
                return NotFound();
            }
            return View(lojasModel);
        }

       /// <summary>
       /// método de edicao de uma loja para o banco de dados
       /// </summary>
       /// <param name="id"></param>
       /// <param name="lojasModel"></param>
       /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Localizacao,Seguimento,Telefone")] LojasModel lojasModel)
        {
            if (id != lojasModel.Id)
            {
                return NotFound();
            }
            //criando condição : se o valor da modelstate diferente de  valida o if ira passar os comandos de cadastro

            if (!ModelState.IsValid)
            {
                //o programa tenta fazer o update no banco e salvar as mudanças
                try
                {
                    
                    _context.Update(lojasModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LojasModelExists(lojasModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lojasModel);
        }



        // GET: LojasModels/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lojas == null)
            {
                return NotFound();
            }

            var lojasModel = await _context.Lojas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lojasModel == null)
            {
                return NotFound();
            }

            return View(lojasModel);
        }

        // POST: LojasModels/Delete/5
        /// <summary>
        /// método para confirmação de deleção
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lojas == null)
            {
                return Problem("Erro ao apagar as informações, tente novamente mais tarde");
            }
            var lojasModel = await _context.Lojas.FindAsync(id);
            if (lojasModel != null)
            {
                _context.Lojas.Remove(lojasModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LojasModelExists(int id)
        {
          return (_context.Lojas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjetoFinal_RodrigoPaulino/Controllers/ProdutosModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoFinal_RodrigoPaulino.Data;
using ProjetoFinal_RodrigoPaulino.Models;

namespace ProjetoFinal_RodrigoPaulino.Controllers
{
    public class ProdutosModelsController : Controller
    {
        private readonly BancoContext _context;

        public ProdutosModelsController(BancoContext context)
        {
            _context = context;
        }

        // GET: ProdutosModels
        public async Task<IActionResult> Index()
        {
            var bancoContext = _context.Produtos.Include(p => p.Lojas);
            return View(await bancoContext.ToListAsync());
        }

        // GET: ProdutosModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtosModel = await _context.Produtos
                .Include(p => p.Lojas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtosModel == null)
            {
                return NotFound();
            }

            return View(produtosModel);
        }

        // GET: ProdutosModels/Create
        public IActionResult Create()
        {
            ViewData["IdLoja"] = new SelectList(_context.Lojas, "Id", "Nome");
            return View();
        }

        // POST: ProdutosModels/Create
        /// <summary>
        /// Quinto passo será criar as actions das paginas de cadastro, ediçao  e deleção 
        /// e a criação das views de cada action
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdLoja,NomeProduto,Tamanho,Cor,Valor")] ProdutosModel produtosModel)
        {
            produtosModel.NomeProduto = produtosModel.NomeProduto.ToUpper();
            _context.Add(produtosModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            ViewData["IdLoja"] = new SelectList(_context.Lojas, "Id", "Localizacao", produtosModel.IdLoja);
            
        }

        // GET: ProdutosModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtosModel = await _context.Produtos.FindAsync(id);
            if (produtosModel == null)
            {
                return NotFound();
            }
            ViewData["IdLoja"] = new SelectList(_context.Lojas, "Id", "Localizacao", produtosModel.IdLoja);
            return View(produtosModel);
        }

        // POST: ProdutosModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdLoja,NomeProduto,Tamanho,Cor,Valor")] ProdutosModel produtosModel)
        {
            if (id != produtosModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(produtosModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutosModelExists(produtosModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdLoja"] = new SelectList(_context.Lojas, "Id", "Localizacao", produtosModel.IdLoja);
            return View(produtosModel);
        }

        // GET: ProdutosModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtosModel = await _context.Produtos
                .Include(p => p.Lojas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtosModel == null)
            {
                return NotFound();
            }

            return View(produtosModel);
        }

        // POST: ProdutosModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produtos == null)
            {
                return Problem("Entity set 'BancoContext.Produtos'  is null.");
            }
            var produtosModel = await _context.Produtos.FindAsync(id);
            if (produtosModel != null)
            {
                _context.Produtos.Remove(produtosModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutosModelExists(int id)
        {
          return (_context.Produtos?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpGet]
        public async Task<IActionResult> ExibirLista()
        {
            List<ProdutosModel> produtos = await _context.Produtos.ToListAsync();
            return View ("Edit", produtos);
        }
    }
}

ProjetoFinal_RodrigoPaulino/Views/Shared/_Layout.cshtml
<!--Mudamos o titulo e os nav´s bar-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de busca de Produtos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css"/>
 

    <link rel="stylesheet" href="~/ProjetoFinal_RodrigoPaulino.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema de busca de Produtos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre o Projeto</a>
                        </li>
                        <li class="nav-item">
                            <!--Traçamos a rota da controller para Lojas e a action para Index-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="LojasModels" asp-action="Index">Lojas</a>
                        </li>
                         <li class="nav-item">
                            <!--Traçamos a rota da controller para Lojas e a action para Index-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProdutosModels" asp-action="Index">Produtos</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <!--Mudamos a menssagem para o nome do sistema -->
            &copy; 2022 - Sistema de busca de Produtos  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>